export const BusinessTypes = {

    GET_BUSINESS_START: "GET_BUSINESS_START",
    GET_BUSINESS_COMPLETE: "GET_BUSINESS_COMPLETE",
    GET_BUSINESS_ERROR: "GET_BUSINESS_ERROR",

    CREATE_BUSINESS_START: "CREATE_BUSINESS_START",
    CREATE_BUSINESS_COMPLETE: "CREATE_BUSINESS_COMPLETE",
    CREATE_BUSINESS_ERROR: "CREATE_BUSINESS_ERROR",

    DELETE_BUSINESS_START: "DELETE_BUSINESS_START",
    DELETE_BUSINESS_COMPLETE: "DELETE_BUSINESS_COMPLETE",
    DELETE_BUSINESS_ERROR: "DELETE_BUSINESS_ERROR",

    UPDATE_BUSINESS_START: "UPDATE_BUSINESS_START",
    UPDATE_BUSINESS_COMPLETE: "UPDATE_BUSINESS_COMPLETE",
    UPDATE_BUSINESS_ERROR: "UPDATE_BUSINESS_ERROR",

    GET_PERSONS_START: "GET_PERSONS_START",
    GET_PERSONS_COMPLETE: "GET_PERSONS_COMPLETE",
    GET_PERSONS_ERROR: "GET_PERSONS_ERROR",

    CREATE_PERSON_START: "CREATE_PERSON_START",
    CREATE_PERSON_COMPLETE: "CREATE_PERSON_COMPLETE",
    CREATE_PERSON_ERROR: "CREATE_PERSON_ERROR",

    DELETE_PERSON_START: "DELETE_PERSON_START",
    DELETE_PERSON_COMPLETE: "DELETE_PERSON_COMPLETE",
    DELETE_PERSON_ERROR: "DELETE_PERSON_ERROR",

    UPDATE_PERSON_START: "UPDATE_PERSON_START",
    UPDATE_PERSON_COMPLETE: "UPDATE_PERSON_COMPLETE",
    UPDATE_PERSON_ERROR: "UPDATE_PERSON_ERROR"



};